#!/usr/bin/env python3

##########################################################################################
# Developers: 	Icaro Alzuru and Aditi Malladi
# Project: 		HuMaIN (http://humain.acis.ufl.edu)
# Description: 	Randomly selects n specimens from the unprocessed specimens
##########################################################################################
# Copyright 2019    Advanced Computing and Information Systems (ACIS) Lab - UF
#                   (https://www.acis.ufl.edu/)
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file 
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the 
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific language governing permissions 
# and limitations under the License.
##########################################################################################

import os, sys, argparse, glob, random
import pandas as pd

from humain.constants import *
from humain.utils import *
##############################################################################################################################################################
if __name__ == '__main__':
	""" Randomly selects n specimens from the unprocessed specimens"""
	# Read arguments
	parser = argparse.ArgumentParser("Randomly selects n specimens from the unprocessed specimens")
	parser.add_argument('-i','--init_list_file',action="store", required=True, help="File containing the list of specimens in the entire set.")
	parser.add_argument('-n','--subset_size',action="store", required=True, help="Number of specimens to select in every subset.")
	parser.add_argument('-ht','--h_ar_task',action="append", required=False, help="Accept/Reject directory generated by a human-centered task. Rejected specimens are discarded.")
	parser.add_argument('-mt','--m_ar_task',action="append", required=False, help="Accept/Reject directory generated by a machine task. Rejected specimens will be reprocessed.")
	parser.add_argument('-o', '--output_file', action="store", required=True, help="Text file where the list of selected specimens will be saved.")
	args = parser.parse_args()
	# Usage example:
	# python3 subset.py -i /home/ialzuru/Fall2019/HuMaIN_Simulator/datasets/aocr_mix100/specimen_list.txt -n 20 -ht consensus -mt rb_dict_extr -o /home/ialzuru/Fall2019/HuMaIN_Simulator/selfie/results/recorded_by_hitl/iteration_1.txt

	################################################################################################################################
	# ARGUMENTS VALIDATIONS
	################################################################################################################################
	#### INPUTS
	# args.init_list_file
	verify_file( args.init_list_file, 'The file with the original list of specimens (' + args.init_list_file + ') was not found: ', parser, 1 )
	# args.subset_size
	subset_size = 0
	try:
		subset_size = int(args.subset_size)
		if (subset_size < 1):
			raise ValueError('Invalid subset size.')
	except:
		print('Error: The specified subset size is invalid.\n')
		parser.print_help()
		sys.exit(2)
	# args.output_file
	results_dir = os.path.dirname( args.output_file )
	verify_dir( results_dir, 'The directory of the output file (' + args.output_file + ') does not exist.', parser, 3 )	

	##########################################################################################		
	# GENERATE THE FULL LIST AND SET OF ORIGINAL SPECIMENS
	with open(args.init_list_file) as f_orig:
		lines = f_orig.readlines()
	specimens_full_list = [line.strip() for line in lines] 
	specimens_full_set = set(specimens_full_list)

	##########################################################################################		
	# GET THE LIST OF ITERATIONS CURRENTLY EXECUTED
	iteration_items = glob.glob( results_dir + "/iteration_*" )
	iteration_dirs = []
	for item in iteration_items:
		if os.path.isdir( item ):
			iteration_dirs += [ item ]

	##########################################################################################		
	# GENERATE THE LIST OF ACCEPTED SPECIMENS
	accepted_specimens = set()
	# Human self-aware tasks
	for h_task in args.h_ar_task:
		for iter_dir in iteration_dirs:
			accepted_file = iter_dir + "/" + h_task + "/accepted/accepted.tsv"
			verify_file( accepted_file, 'Accepted file was not found for task ' + h_task + ' and iteration directory ' + iter_dir +  '.', None, 4 )
			# Open the file and add to the set the 
			df_a = pd.read_csv( accepted_file, sep='\t', names = ['specimen', 'value'] )
			df_a.fillna('', inplace= True)
			accepted_specimens = accepted_specimens | set(df_a['specimen'])
	# Machine self-aware tasks
	for m_task in args.m_ar_task:
		for iter_dir in iteration_dirs:
			accepted_file = iter_dir + "/" + m_task + "/accepted/accepted.tsv"
			verify_file( accepted_file, 'Accepted file was not found for task ' + m_task + ' and iteration directory ' + iter_dir +  '.', None, 4 )
			# Open the file and add to the set the 
			df_a = pd.read_csv( accepted_file, sep='\t', names = ['specimen', 'value'] )
			df_a.fillna('', inplace= True)
			accepted_specimens = accepted_specimens | set(df_a['specimen'])
			
	##########################################################################################		
	# GENERATE THE LIST OF REJECTED SPECIMENS
	rejected_specimens = set()
	# Human self-aware tasks
	for h_task in args.h_ar_task:
		for iter_dir in iteration_dirs:
			rejected_file = iter_dir + "/" + h_task + "/rejected/rejected.txt"
			verify_file( rejected_file, 'Rejected file was not found for task ' + h_task + ' and iteration directory ' + iter_dir +  '.', None, 4 )
			# Open the file and add to the set the 
			df_a = pd.read_csv( rejected_file, sep='\t', names = ['specimen', 'value'] )
			df_a.fillna('', inplace= True)
			rejected_specimens = rejected_specimens | set(df_a['specimen'])

	##########################################################################################		
	# GENERATE THE LIST OF REJECTED SPECIMENS
	available_specimens = specimens_full_set - accepted_specimens - rejected_specimens
	if len(available_specimens) == 0:
		sys.exit(-1)
	selected_specimens = random.sample( available_specimens, subset_size )
	
	##########################################################################################		
	# SAVE THE SUBSET OF SELECTED SPECIMENS
	output_text = ""
	for specimen in selected_specimens:
		output_text += specimen + "\n"
	with open(args.output_file, "w+") as f_o:
		f_o.write( output_text )

	##########################################################################################		
	# GENERATE THE LIST OF SPECIMENS THAT STILL NEED TO BE PROCESSED (NOT INCLUDING THE SELECTED)
	available_specimens = available_specimens - set(selected_specimens)
	
	##########################################################################################		
	# SAVE THE SUBSET OF SELECTED SPECIMENS
	output_text = ""
	for specimen in available_specimens:
		output_text += specimen + "\n"
	with open( os.path.dirname(args.output_file) + "/remaining_specimens.txt", "w+" ) as f_r:
		f_r.write( output_text )